# Generated by Django 3.0.3 on 2020-02-24 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_order_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created']},
        ),
    ]
