# Generated by Django 3.1.7 on 2021-03-19 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20210314_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='university',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=56, null=True, verbose_name='Аббревиатура'),
        ),
        migrations.AlterField(
            model_name='university',
            name='abbreviation_en',
            field=models.CharField(blank=True, max_length=56, null=True, verbose_name='Аббревиатура'),
        ),
        migrations.AlterField(
            model_name='university',
            name='abbreviation_ru',
            field=models.CharField(blank=True, max_length=56, null=True, verbose_name='Аббревиатура'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name_en',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Имя(анг)'),
        ),
        migrations.AlterField(
            model_name='university',
            name='name_ru',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Имя(рус)'),
        ),
    ]
