# Generated by Django 3.1.7 on 2021-03-19 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20210319_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deep_link',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Ссылка'),
        ),
    ]
