# Generated by Django 3.0.3 on 2020-02-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramuser',
            name='language',
            field=models.CharField(choices=[('uz', "O'zbekcha"), ('en', 'English'), ('ru', 'Русский')], default='uz', max_length=64),
        ),
    ]
