# Generated by Django 3.0.3 on 2021-03-10 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210310_2210'),
        ('bot', '0002_auto_20200224_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.University'),
        ),
    ]
