# Generated by Django 3.1.7 on 2021-03-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_auto_20210311_0139'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='offset',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
