# Generated by Django 3.1.7 on 2021-03-26 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bot', '0005_command_offset'),
    ]

    operations = [
        migrations.AddField(
            model_name='command',
            name='product',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
